### ISSUE TITLE
Cmake on Windows says "Could NOT find LAPACK"

### ISSUE THREAD

**Issue by omgitsraven** [jlblancoc/suitesparse-metis-for-windows#96] opened 2020-01-03 05:04 UTC
The readme's instructions say that the "Install LAPACK & BLAS" step is "Only for Linux/Mac", but I'm on Windows 10 and pressing the Configure button in CMake GUI results in the following output:
```
The C compiler identification is MSVC 18.0.40629.0
The CXX compiler identification is MSVC 18.0.40629.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Using default C++ standard 11
Setting default CMAKE_INSTALL_PREFIX to: C:/Users/Hazel/Downloads/suitesparse-metis-for-windows-1.5.0/build/install
Looking for execinfo.h
Looking for execinfo.h - not found
Looking for getline
Looking for getline - not found
Could NOT find LAPACK (missing: LAPACK_DIR)
Looking for sgemm_
Looking for sgemm_ - not found
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Could NOT find BLAS (missing: BLAS_LIBRARIES) 
Could NOT find BLAS (missing: BLAS_LIBRARIES) 
LAPACK requires BLAS
A library with LAPACK API not found. Please specify library location.
CMake Error at CMakeLists.txt:241 (message):
  lapack not found
```
Why are they described as not a requirement on Windows?

**Comment by NeroBurner** [comment] 2020-01-03 09:22
Our README.md is out of date, unfortunately.

duplicate of: https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/70#issuecomment-568252934

> we got a lapack dll checked into this project
> 
> https://github.com/jlblancoc/suitesparse-metis-for-windows/tree/master/lapack_windows/x64
> 
> Without hunter you can set LAPACK_DIR to this folder to provide the dependency.
> 
> With hunter you can look in the cmake configure status messages. There hunter also tells you where the dependencies are installed to



essentially, either use `HUNTER_ENABLED=ON` or use `LAPACK_DIR=path/to/lapack-config.cmake`

**Comment by omgitsraven** [comment] 2020-01-03 17:11
That seems to have gotten me past step 4, thank you!

Does that mean that in step 7, I should add the full path to `/lapack_windows/x64` to the `PATH`? (The folders that it's suggesting to add don't seem to exist.)

**Comment by NeroBurner** [comment] 2020-01-03 21:14
Either that or copy the dll to your executable. Windows and dependencies isn't the easiest to manage in my opinion

On January 3, 2020 6:11:16 PM GMT+01:00, RavenWorks <notifications@github.com> wrote:
>That seems to have gotten me past step 4, thank you!
>
>Does that mean that in step 7, I should add the full path to
>`/lapack_windows/x64` to the `PATH`? (The folders that it's suggesting
>to add don't seem to exist.)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/96#issuecomment-570635384

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2020-01-21 09:19 UTC
