### ISSUE TITLE
Unresolved external: METIS

### ISSUE THREAD

**Issue by plumonito** [jlblancoc/suitesparse-metis-for-windows#7] opened 2015-05-06 14:38 UTC
Hi,
Compilation with Metis goes ok but when I compile the cholmod example it says

> libcholmod.lib(cholmod_metis.o.obj) : error LNK2019: unresolved external symbol _METIS_NodeComputeSeparator referenced in function _cholmod_metis_bisector

I'm using SuiteSparse 4.4.3 and I've tried Metis 5.0 and 5.1.

**Comment by plumonito** [comment] 2015-05-06 14:44
I found some very old references to such a problem from users trying to compile Octave (https://github.com/Homebrew/homebrew-science/issues/128). They mention that SuiteSparse should be compiled with Metis 4 and not 5. But Metis 4 has no cmake file. Which Metis are you using?

**Comment by jlblancoc** [comment] 2015-05-12 21:33
It seems to me that the problem is related to an "outdated" part of SuiteSparse caused by an API change in METIS. Have you tried this patch?? http://www.cise.ufl.edu/research/sparse/cholmod/metis.patch

I'll close the issue, reopen it if that was not the problem. 

Un saludo!

**Comment by aniskacem** [comment] 2016-02-02 10:25
Hello Jiblancoc, 

I am using your suitesparse for windows with visual studio 2013.The compilation was okay but when I wanted to use it in another project I got this link error : 
error LNK2001: unresolved external symbol dtrsv_	{Path_to_Project}\libcholmod.lib(cholmod_super_solve.o.obj)	
I have added all dependencies for my project (Inculde directories, library directories and libs ...) but I have still the same problem. Can you help with this problem please ? 

Best regards,

**Comment by ehsan-azimi** [comment] 2016-05-19 06:25
This link does not work: http://www.cise.ufl.edu/research/sparse/cholmod/metis.patch

Could you please help us with this?

**Comment by jlblancoc** [comment] 2016-05-19 09:37
@ehsan-azimi What's exactly the problem? Please, describe in detail your compilation (OS, compiler,...), attach your `CMakeCache.txt` and explain what's the error / problem you have.

**Comment by ehsan-azimi** [comment] 2016-05-19 15:54
Hi, thank you for your response. OS: Win7, Compilation MVS 14 and I receive the following errors.
I thought it might be related to the "metis.patch" that was mentioned in the instructions. However, the link to the patch is broken and does not work. Could you please let me know your thoughts...

3>libcholmod.lib(cholmod_memory.o.obj) : error LNK2019: unresolved external symbol SuiteSparse_malloc referenced in function cholmod_malloc
3>libcholmod.lib(cholmod_memory.o.obj) : error LNK2019: unresolved external symbol SuiteSparse_calloc referenced in function cholmod_calloc
3>libcholmod.lib(cholmod_memory.o.obj) : error LNK2019: unresolved external symbol SuiteSparse_realloc referenced in function cholmod_realloc
3>libcholmod.lib(cholmod_memory.o.obj) : error LNK2019: unresolved external symbol SuiteSparse_free referenced in function cholmod_free
3>libcholmod.lib(cholmod_error.o.obj) : error LNK2019: unresolved external symbol SuiteSparse_config referenced in function cholmod_error
3>libcholmod.lib(cholmod_csymamd.o.obj) : error LNK2001: unresolved external symbol SuiteSparse_config
3>libccolamd.lib(ccolamd.obj) : error LNK2001: unresolved external symbol SuiteSparse_config
3>libcolamd.lib(colamd.obj) : error LNK2001: unresolved external symbol SuiteSparse_config
3>libcholmod.lib(cholmod_super_numeric.o.obj) : error LNK2019: unresolved external symbol SuiteSparse_time referenced in function c_cholmod_super_numeric
fatal error LNK1120: 6 unresolved externals

**Comment by letienhung** [comment] 2016-05-19 17:46
Here is the link for the metis's patch:
[https://drive.google.com/file/d/0B-rV85pVXDToNjFpZWpKYTc2VUU/view?usp=sharing](url)

As I see, the patch is no longer needed for current suitsparse project. I compiled 1.31 version with metis 5.1 without problems.

**Comment by spyd3rweb** [comment] 2016-12-23 21:30
You had already mentioned it above, but using Metis 4.0.3 resolved the issue. I was able to use version 1.3.1 and merged metis-4.0.3 with the metis folder as stated in jiblancoc's build instruction 3.

**Comment by jlblancoc** [comment] 2018-02-04 01:35
This one should be fixed since long time ago... closing.

**Closed by jlblancoc** 2018-02-04 01:35 UTC

**Comment by aschier** [comment] 2019-04-02 14:34
I've got the same problem with suitesparse-metis 1.4.0 used with ceres (1.14.0) in Visual Studio 2017

    1>libcholmod.lib(cholmod_metis.o.obj) : error LNK2019: unresolved external symbol METIS_NodeND referenced in function cholmod_metis
    1>libcholmod.lib(cholmod_metis.o.obj) : error LNK2019: unresolved external symbol METIS_ComputeVertexSeparator referenced in function cholmod_metis_bisector

On another PC with VS 2015 it works. I am not sure if every CMake option in the projects is the same, but it looks like suitesparse-metis should always export these symbols?

**Comment by NeroBurner** [comment] 2019-04-03 09:45
@aschier please open a new issue referencing this one and give a way to reproduce this error. Minimal example would also be very much appreciated
